---
- name: create user test and set password
  hosts: test   # Group name test
  # Privilege escalation is not required since playbook run as root 

  tasks:
    - name: create the user test
      user:   # Module for user creation
        name: test
        state: present 
        password: "{{ 'admin123' | password_hash('sha512') }}" 
