---
- name: deploy a jinja loop
  hosts: test
  become: yes
  vars:
    users:
      - user1
      - user2
      - root
      - user3

  tasks:
    - name: deploy user template
      template:
        src: 04-jinja-condition.j2
        dest: /etc/users-condition
