---
- name: User creation
  hosts: test
  become: yes
  #vars:
  #  user_name: joe
  #vars_files:
  #  - vars.yml
    

  tasks:
    - name: Create the user {{ user_name }}
      user:
        name: "{{ user_name }}"
        state: present
